### PR TITLE
Create LICENSE and NOTICE files

### PR DESCRIPTION
**Pull request by christopherclark**

### CODE REVIEW

**Comment by kdykeman** [comment]
@njbennett Can you help get this pull request merged?

**Comment by njbennett** [comment]
I'm no longer on the @cloudfoundry/cf-release-integration integration team but if you drop this in their channel and ping their PM they can get you hooked up. (They're in the OSS slack.)

That said:
What software are you trying to release that depends on this @beckettsean? CATs should not be run on production systems, which means it's likely not appropriate for customers to use. Is there some other product that's using this now?

**Comment by njbennett** [comment]
To the RelInt team: I would merge this back in with CATs. The overhead of monitoring an additional repo for PRs and whatnot probably isn't worth whatever benefit having it in a separate repo hypothetically provides to reusability.

**Comment by beckettsean** [comment]
IIRC, the dependency was in the tickets for the Platform Automation codebase. I can certainly understand that CATS shouldn't be distributed code, so perhaps it was an oversight on their part that it ended up in the scan root. @kdykeman any thoughts?

**Comment by beckettsean** [comment]
I checked and I did not recall correctly, I cannot find the ticket that originated this request. Given that the OSL team is not blocked, perhaps this was resolved upstream and the incorrect dependency removed.

I'm fine with merging or not merging this PR, apologies for the kerfuffle.

**Comment by kdykeman** [comment]
It's a dependency of [cf-cli](https://github.com/cloudfoundry/cli/blob/b93f32cc4453869a556e10b82e666d6b31934809/Gopkg.lock#L152-L159). It could be that we should be doing something different in LicenseFinder if this isn't actually being used/shipped in some way. Regardless, it's a public repo and should have a license, otherwise, nobody else has the rights to use it in their product.

**Comment by njbennett** [comment]
I'm still worried that I appear to be the closest thing that this thing has to a maintainer, and suspicious about people including it in product code that's being shipped to customers... but I can see situations where it would be reasonable to package a system's tests with its code, so, sure, PR merged.

**Pull request merged**
